name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: pre-test-and-build

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check branch
        uses: actions/checkout@v3

      - name: Set up Js Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build storybook
        run: npm run build-storybook

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
